### ISSUE TITLE
Code depends on oauth2client.contrib.appengine but not installed by following instructions

### ISSUE THREAD

**Issue by usul83** [GoogleCloudPlatform/reliable-task-scheduling-compute-engine-sample#18]
This code depends on oauth2client.contrib.appengine but this is not installed by following instructions in the readme, i.e. running:
'pip install -t gae/lib/ google-api-python-client'

I fixed it with a further 'pip install -t gae/lib/ oauth2client'. 

Not sure if affects it, but I did this inside a virtual environment to avoid pip issues with other installed packages (i.e. not installing things due to clashes in requirements).

Here is the traceback:
(/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py:263)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/xxxx/xxxx/main.py", line 21, in <module>
    from pubsub_utils import publish_to_topic
  File "/base/data/home/apps/xxxx/xxxxxx/pubsub_utils.py", line 21, in <module>
    import oauth2client.contrib.appengine as gae_oauth2client
ImportError: No module named oauth2client.contrib.appengine

**Comment by Zukkster** [comment]
I had the same issue. Tried that fix and still getting the same error did you have re deploy the app of anything?

**Comment by Zukkster** [comment]
Required the same on the VM as a well

**Comment by jianping-roth** [comment]
Thank you for sharing your fix. Zukkster.

**Comment by jkobti** [comment]
Am I supposed to run this on vm instance?

**Comment by jpatokal** [comment]
The sample has been updated to use Cloud Scheduler, so App Engine is no longer necessary.
